### ISSUE TITLE
No entity label on bar graphs for total increasing entities

### ISSUE THREAD

**Issue by rct** [alexarch21/history-explorer-card#78] opened 2022-10-23 16:16 UTC
I think the bar graph for total increasing entities is great and very useful.  However, I noticed it lacks any sort of label/legend for what entity it is showing.  

![image](https://user-images.githubusercontent.com/38770/197403229-4ebea629-0d49-465e-8fa0-a45603de3f4a.png)

The image in this repo's README shows two graphs without a label/legend.

![image](https://user-images.githubusercontent.com/60828821/193383950-53242b11-d467-42ba-9859-3b3df0b0dcb8.png)
 
Is this by design (the user need to hover over a bar to see what it is?)

**Comment by alexarch21** [comment] 2022-10-23 17:16
No, not by design, but mostly because I forgot to add them...

![image](https://user-images.githubusercontent.com/60828821/197405921-97402933-d35d-4c65-b50b-2072f9ec9b72.png)

**Comment by alexarch21** [comment] 2022-10-27 02:02
Fixed in v1.0.29.

**Closed by alexarch21** 2022-10-27 02:02 UTC
