### ISSUE TITLE
Any plans to support HA statistics?

### ISSUE THREAD

**Issue by dm82m** [alexarch21/history-explorer-card#7] opened 2022-01-25 09:36 UTC
Hey Alex,

first of all: thank you very much for your work!

And then a question: currently your chart takes the last saved data. Is there any plan to support also the statistics?

Best,
Dirk

**Comment by dm82m** [comment] 2022-01-25 09:46
the statistics graph shows older data compared to your history card:

![image](https://user-images.githubusercontent.com/736311/150952613-367cf8bb-bbee-40a2-b86c-ab6a62c39702.png)

![image](https://user-images.githubusercontent.com/736311/150952649-02151b74-7f0d-414b-aa85-2c1b680464e0.png)

**Comment by alexarch21** [comment] 2022-01-25 20:08
Hi, long term statistics support wasn't on my radar at this time. How long is your normal recorder data retention time (ie. purge_keep_days in the recorder config) ? The card seems to be showing less than a day, that's definitely not normal. What happens when you scroll left or increase the viewed time range to a few days or a week?

**Comment by dm82m** [comment] 2022-01-25 20:10
Default it shows the last 10 days. But no worries I just wanted to asked if statistics support is plannedy

**Comment by alexarch21** [comment] 2022-01-26 02:48
Ah okay, I'll look into it. I'll mark this as a FR.

**Comment by jnxxx** [comment] 2022-04-23 10:26
I just found this card and I like it a lot.
+1 for statistics data, to make it even better.

I believe statistics was made as a lightweight method to store long-term data (in lower resolution). So, quite relevant for a History Explorer.
And with this scrolling view, really nice if you could go further back.

Additionally, if you can get statistics data it would be neat to have a delta option for metered values, like an electricity, heat, gas or water meter. There it is not so much the value that is of interest but instead the change, growth or decline.

**Comment by alexarch21** [comment] 2022-07-14 09:23
Yeah, statistics are on the backlog. I also think that supporting them would be very beneficial. The problem is that supporting them in a good way, seamlessly integrated with normal history and the caching and scrolling etc, is a considerably amount of work. Especially since HA exposes them in a completely different way than normal history, for whatever reason.

So this is something that will definitely come to the history explorer card, but I can't guarantee when exactly.

**Comment by rct** [comment] 2022-10-10 18:14
> The problem is that supporting them in a good way, seamlessly integrated with normal history 

This seems like something where there should be support in the HA integrations that provide history and statistics. From a user's perspective why are they separate and distinct?

Access to the statistics data in HA is so poor right now that there is a lot of room for improvement. So any access to statistics data beyond the current statistics card would be a help.

**Comment by FrnchFrgg** [comment] 2022-10-10 21:24
Apex-charts card already supports long-term statistics. See https://github.com/RomRider/apexcharts-card/blob/master/src/graphEntry.ts#L257 for the if/else clauses with first statistics fetching then normal history fetching. AFAICT the difference is not much and mostly in `_fetchStatistics` vs `_fetchRecent` even though the value of the datapoint then comes from `item[period]` instead of `item.state` (and there is a difference too for the datetime). To me it seems that retrofitting the statistics fetching into a format understood by the existing `history-explorer-card` data handling is not too hard.

I have no time right now but maybe at one point in the next month I'll get to it.

**Comment by alexarch21** [comment] 2022-10-10 22:00
The data fetching itself is not the issue and is already done. The problem comes from the way how the card does the streaming by issuing async fetches. HA reacts weird when issuing multiple statistics and history fetches at the same time. Requests have a tendency to fail randomly and need to be re-requested, at least on the SQLite backend. Besides that, the local caching structure the card uses also needs to be adjusted with a dynamic slot allocation scheme (rather than the current fixed one) so to efficiently handle entities with and without long range stats shown in the same graph or view.

**Comment by alexarch21** [comment] 2022-10-10 22:08
> This seems like something where there should be support in the HA integrations that provide history and statistics. From a user's perspective why are they separate and distinct?
> 
> Access to the statistics data in HA is so poor right now that there is a lot of room for improvement. So any access to statistics data beyond the current statistics card would be a help.

When you look at the HA source, it is pretty obvious that the entire statistics thing was bolted onto the existing system as a completely separate entity, with no attempt made to integrate it into the existing history subsystem. This concept of two entirely separate history gathering and request subsystems then carried over to the UX. I don't really understand why it was done that way, but I guess they probably had their reasons.

**Comment by alexarch21** [comment] 2022-10-30 14:00
V1.0.30 adds (experimental) seamless statistics support.

See this post on the HA forums for more info:
https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/332

Feedback welcome.

**Closed** 2022-11-09 02:58 UTC
Labels: enhancement
