### ISSUE TITLE
UX improvment Easier access to 10 days (recorder default)

### ISSUE THREAD

**Issue by rct** [alexarch21/history-explorer-card#71] opened 2022-10-15 17:23 UTC
The default is for recorder to store 10 days of history, but the dropdown date range choices are 1 week and 2 weeks. 

Ideally there would be an easy way to see all available history.  AFAICT the Zoom function snaps to 1 week when I select 2 weeks and try to rubber band out 10 days to go full screen on the available data.

UX Bonus: Don't show choices like 3 weeks/1 month if that data doesn't exist in history (and the front end could tell how much history is available.)

EDIT: if there were access to the statistics storage, or recorder implementation ever changed to allow more flexible retention periods, then I suppose this would be a moot point.

**Comment by alexarch21** [comment] 2022-10-15 18:29
> Ideally there would be an easy way to see all available history. AFAICT the Zoom function snaps to 1 week when I select 2 weeks and try to rubber band out 10 days to go full screen on the available data.

Yeah, that's by design. The range will snap to the nearest value available through the UI (in the dropdown). The idea is to always have an easily identifiable range active, discoverable and reproduceable any time on the UI. It was specifically designed in a way to avoid odd values for the range. The exception being anything below 1 hour, because there's no real other way to do it there (that's why the dropdown shows <1H in that case).

Is it really that much of an issue that the history shows 2 weeks while only 10 days have valid data ? Or to go even further, isn't pretty much everybody changing the default 10 days retention period anyway ?

> UX Bonus: Don't show choices like 3 weeks/1 month if that data doesn't exist in history (and the front end could tell how much history is available.)

Unfortunately the front end does not have access to that information.

> EDIT: if there were access to the statistics storage, or recorder implementation ever changed to allow more flexible retention periods, then I suppose this would be a moot point.

Statistics support is on the roadmap anyway.

**Comment by rct** [comment] 2022-10-16 22:08
> Is it really that much of an issue that the history shows 2 weeks while only 10 days have valid data ? Or to go even further, isn't pretty much everybody changing the default 10 days retention period anyway ?

I've left recorder at the default 10 days.  I don't know how many have changed that.

I also send data to InfluxDB. I'm also still using the default sqlite instead of mysql/mariadb.  

I have lots of sensors. (I had some early sqlite3 performance problems with my first install 2+ years ago, so I've left it alone.)  

Things have changed a lot, so might be time for me to rethink that. Before some of the db optimizations work in the last year or so, done my db was over 3GB.  Now it's running at a much more reasonable 1.2GB.  I've also cleaned up some of my template sensors and many integrations have gotten smarter about how much stuff gets written to the db. 

See it I was wondering if there are details I'm not seeing in the data because the display has been sized for 14 days. I don't know how much of a problem it really is with the decimation, but with 10 days displayed in space for 14, almost 30% of the screen width is empty.

**Comment by alexarch21** [comment] 2022-10-23 02:36
I'm going to close this, as the recorder details are a little out of scope for this card. And as said above, I don't think using a 2 week view on a 10 day purge period is much of a usability problem.

**Closed by alexarch21** 2022-10-23 02:36 UTC
