### ISSUE TITLE
defaultTimeRange : some values are not working

### ISSUE THREAD

**Issue by PatrickGlesner** [alexarch21/history-explorer-card#69] opened 2022-10-14 08:18 UTC
Thanks for this wonderful card.

I noticed some values are not working for parameter defaultTimeRange:
3h, 4h, 5h : display 12h
7h -> 11h : display 1 day
13h -> 23h : display 2 days

1h, 2h, 6h, 12h and 24h are correct.

Best regards,
Patrick.

**Comment by alexarch21** [comment] 2022-10-15 18:37
Part of this is by design. Anything above 12H will snap to the nearest range selectable through the range dropdown. Hourly values between 1H and 12H should work though, so that's a bug.

**Comment by alexarch21** [comment] 2022-10-23 02:18
Fixed in V1.0.28 for ranges between 1H and 12H.

**Closed by alexarch21** 2022-10-23 02:18 UTC
