### ISSUE TITLE
Incorrect value in bar view

### ISSUE THREAD

**Issue by Yasp0** [alexarch21/history-explorer-card#106] opened 2022-12-12 15:00 UTC
I use the current history-exporer-card to view my power consumption:

```
type: custom:history-explorer-card
axisAddMarginMin: false
decimation: accurate
header: Dagverbruik
defaultTimeRange: 1d
uiLayout:
  selector: hide
graphs:
  - type: bar
    entities:
      - entity: sensor.elektra_dagverbruik
        name: Totaal
        color:
          '0.0': '#136734'
          '0.25': '#1c8c37'
          '0.5': '#92c11f'
          '0.75': '#faeb02'
          '1.0': '#f7b232'
          '1.25': '#ea5b0b'
          '1.5': '#bc1622'
```

As seen in the screenshot at 14:30 there is a false number of very high power usage. 

![Screenshot 2022-12-12 at 15 59 19](https://user-images.githubusercontent.com/5689226/207078218-7771743f-d8b8-42cf-b9c7-4063424d3529.png)

In this screenshot the line shows the actual correct usage.

![Screenshot 2022-12-12 at 15 55 08](https://user-images.githubusercontent.com/5689226/207078319-fd3d00c0-7bfa-40dd-bcf4-bfd29e98cb86.png)

Any idea what is going on?

Using most recent version of history-explorer-card (1.0.40).

**Comment by alexarch21** [comment] 2022-12-12 17:45
Could you export the last 24 hours of this sensor as a CSV and post it here please.

**Comment by Yasp0** [comment] 2022-12-13 08:44
Here is the export. I just had again a very high odd number.

[entities-2022-12-13_09_42_59.csv](https://github.com/alexarch21/history-explorer-card/files/10215985/entities-2022-12-13_09_42_59.csv)

![Screenshot 2022-12-13 at 09 44 01](https://user-images.githubusercontent.com/5689226/207268461-7ac53f4f-3615-4c4f-9a4d-1969d5c9b82a.png)

**Comment by alexarch21** [comment] 2022-12-13 14:50
Thanks. The reason this is happening is because your energy data contains invalid values from time to time. If you open the CSV you'll see empty datasets at the offending time slots. 

Normally the card will ignore unknown or unavailable states, likely from a wifi power meter with intermittent connection problems or from HA restarts. But that's not what is happening with your data. The sets are just empty. The card will (incorrectly) interprete that as a zero reset and that's what causes these high values.

I will add the handling of empty values in the next version to cover cases like this. But your meter outputting empty datasets is definitely not normal and you should check that. It can create other problems beyond this card.

**Comment by alexarch21** [comment] 2022-12-13 15:01
Btw, in the meantime you can probably use the custom data processing option of the card to get rid of these. I'll see if I can write something up quickly later today when I'm back from the office.

**Comment by alexarch21** [comment] 2022-12-17 19:30
Have you tried the above suggestion ? Did it work ?

**Comment by Yasp0** [comment] 2022-12-18 10:40
I added the process parameter but this didn't solve it. In the meantime I also added a different sensor and that one seems to work fine so far.

**Comment by alexarch21** [comment] 2022-12-18 14:11
The process setting I posted above solves the problem for the dataset you sent, I tried and confirmed this here. Make sure to copy it exactly as-is, with all single and double quotes intact. The next version will not directly solve your problem with the empty records, as doing this would induce a breaking change for other users. Your case seems to be very specific and unique, due to your malfunctioning sensor. But the process function should take care of this. In the next release the process function is generally improved, so it should work better with less gaps for cases like yours.

In the end, you definitely need to fix your sensor though to not generate empty datasets.

I'm closing this so far. If you still encounter problems with the upcoming version, feel free to create a new issue.

**Closed by alexarch21** 2022-12-18 14:11 UTC
