### ISSUE TITLE
Is this a data-decimation bug?

### ISSUE THREAD

**Issue by Apfelmousse** [alexarch21/history-explorer-card#183] opened 2023-06-20 08:10 UTC
I'm using your card to display a bunch of temperatures at home. 

This morning  the graphs looked as if the sensors have been dead for some hours. But no - I noticed the graph first draws properly with all the values, and after some seconds a part of the graph is replaced by a straight line. This is a 1-day graph, where decimation should not occur... 

Changing (decimation: false) to (decimation:accurate), zooming in and out always gives the same result, i.e. a straight line where the varying values should be drawn.

cheers
Martin

**Comment by Apfelmousse** [comment] 2023-06-20 08:23
I added two pics, what is displayed first and then after some seconds...

![2023 06 20 - Graph before decimation](https://github.com/alexarch21/history-explorer-card/assets/137155398/405b7b5a-78db-4174-b93d-1c34da8c19ad)
![2023 06 20 - Graph with decimation](https://github.com/alexarch21/history-explorer-card/assets/137155398/558c657f-40c9-4fb7-b919-568b6f444536)

**Comment by alexarch21** [comment] 2023-06-22 22:54
Doesn't look like a decimation problem. 

* Post your card YAML
* Post potential errors in the logs when this happens (HA core log and console log of the browser the card is running on)
* Do you have auto-refresh enabled ?

**Comment by Apfelmousse** [comment] 2023-06-23 08:52
Hi,

I cannot tell if auto-refresh is enabled - I do not remember having activated an option of that name. Where do I have to look for that?

Here is the YAML code (there is a refresh in the code):
`type: custom:history-explorer-card
cardName: Temperatures
defaultTimeRange: 1d
defaultTimeOffset: 1h
decimation: false
refresh:
  interval: 10
lineMode: lines
showUnavailable: true
combineSameUnits: true
axisAddMarginMin: false
axisAddMarginMax: false
lineGraphHeight: 500
entityOptions:
  sensor.licht:
    ymin: 0
    ymax: 1200
  sensor.aussentemperatur:
    ymin: 0
    ymax: 40
  sensor.taupunkt:
    ymin: 0
    ymax: 40
  sensor.balkon:
    ymin: 0
    ymax: 40
`
In the HA core logs I cannot find any event that corresponds to the time when I opened the card.

Here is the console log of Firefox...  the effect is the same on different computers (MacOS, Linux).
`BackgroundUpdate: _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.jsm :: _reasonsToNotScheduleUpdates :: line 241"  data: no] [BackgroundUpdate.jsm:243](resource://gre/modules/BackgroundUpdate.jsm)
PushService: receivedPushMessage: Error notifying app Error: No record for key ID f362d838-481e-4a98-869b-7695a7abab50
    _updateRecordAfterPush resource://gre/modules/PushService.jsm:860
[PushService.jsm:828](resource://gre/modules/PushService.jsm)
TypeError: gRecipeManager is null
2 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null
4 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null
[LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null
2 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null
2 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
    <anonymous> resource://gre/modules/LoginManagerParent.jsm:136
TypeError: gRecipeManager is null
4 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null
2 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null
2 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null
3 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
TypeError: gRecipeManager is null8 [LoginManagerParent.jsm:136:3](resource://gre/modules/LoginManagerParent.jsm)
    <anonymous> resource://gre/modules/LoginManagerParent.jsm:136`

**Comment by Apfelmousse** [comment] 2023-06-23 08:58
I did take out the "refresh: interval: 10" from the YAML, and now it displays fine.

**Comment by alexarch21** [comment] 2023-06-23 11:57
Try to reduce the auto refresh interval to something like 60 seconds and see if that improves things. 10 seconds may overwhelm your database.

**Comment by Apfelmousse** [comment] 2023-06-23 14:21
You probably meant increasing the interval - but that does not work. Tried 60 and 120 seconds, the only difference is that the straight lines appear later. Actually when the refresh is carried out.

**Comment by Apfelmousse** [comment] 2023-06-24 07:35
Yes, its always the same spot - between 24h and 6h (6 hours span)

Here's the YAML with the layout as in my editor. I was using the code-insertion function incorrectly, that killed the layout.

```
type: 
  custom:history-explorer-card
cardName: Temperatures
defaultTimeRange: 3d
defaultTimeOffset: 1h
refresh:
  interval: 10
decimation: false
lineMode: lines
showUnavailable: true
combineSameUnits: true
axisAddMarginMin: false
axisAddMarginMax: false
lineGraphHeight: 500
entityOptions:
  sensor.licht:
    ymin: 0
    ymax: 1200
  sensor.aussentemperatur:
    ymin: 0
    ymax: 40
  sensor.taupunkt:
    ymin: 0
    ymax: 40
  sensor.balkon:
    ymin: 0
    ymax: 40
```

**Comment by alexarch21** [comment] 2023-06-24 11:36
Looks like your database doesn't return values in the affected period on subsequent calls. I never experienced an effect like this.

* What version of HA are you using
* What database engine
* Recorder retention period (in configuration.yaml)
* Size of your database

**Comment by Apfelmousse** [comment] 2023-06-24 14:31
- What version of HA are you using -> 2023.6.2
- What database engine -> default, I didn't change anything after installation of HA
- Recorder retention period (in configuration.yaml) -> canntot find this parameter, should be default
- Size of your database -> where can I find this? It should not be large, I just began using HA 2 weeks ago.

**Comment by alexarch21** [comment] 2023-06-24 20:31
I found a pretty obscure bug with the history / statistics merging code while trying to reproduce your thing. I'm not sure if that is the one causing your problem, but the symptoms look very similar.

Can you try to add this to your config and see if the problem persists: 
```
statistics:
  enabled: false
```
Keep the refresh interval at 10.

**Comment by Apfelmousse** [comment] 2023-06-25 07:15
I put your code in, see the YAML extract below. I guess the order within the YAML is not important.
Unfortunately, no change. I upgraded the core to 2023.6.3, same behaviour (i.e. no change, still the straigt line after some seconds)

```
defaultTimeOffset: 1h
refresh:
  interval: 10
statistics:
  enabled: false
decimation: false
```

**Comment by alexarch21** [comment] 2023-06-25 10:51
Well it was worth a try (and I found another bug that way).

The problem is that I can't reproduce your issue, and as far as I know, noone else ever reported something like this. It's going to be very difficult to proceed with this I'm afraid.

**Comment by Apfelmousse** [comment] 2023-06-25 13:50
Yes, of course. Is there a way to send you the database and/or configuration so you can try to reproduce it?

**Comment by alexarch21** [comment] 2023-06-26 01:27
OK, I found another bug. Not in this card, but in the HA history API. Not entirely clear at this time if this is yours (although the symptoms are again similar), but we're surely catching bugs here ... ;)

What is your local timezone on both the HA server and on the browser you are viewing the card (if different) ?

**Comment by Apfelmousse** [comment] 2023-06-26 09:36
Hi, local time of the browser is CET (central european time)
Time on HA is GMT-5 (Toronto time), as we plan to move the system there.
Shall I try and put HA time to CET, or vice versa?

**Comment by alexarch21** [comment] 2023-06-26 10:59
OK, that is it then. The flatline you are getting is the difference between both timezones. 

Setting both to the same timezone *should* fix this, but maybe not entirely. There might still be an issue, but over a smaller time period, as UTC might also be involved in this. That part of HA is not really documented, so it's hard to determine how exactly something is supposed to behave and if changes to it are intentional or not. That said, it's an important corner case you uncovered here, that needs to be addressed. Not sure when I can do this, this week is going to be very busy. Most likely next weekend.

**Comment by Apfelmousse** [comment] 2023-06-26 13:37
Just tried it out - put the HA to CMT, and now everything is fine! 
Thanks so far. Interesting side effect... normally I wouldn't do that, except maybe if I had to poll an HA via Internet from another timezone.
cheers, Martin

**Comment by alexarch21** [comment] 2023-09-10 03:08
There were some improvements in V1.0.48 pertaining to timezone handling, specifically in situations like this one. I'm closing this now, feel free to open a new issue if things are still weird on the latest version.

**Closed by alexarch21** 2023-09-10 03:08 UTC
