### ISSUE TITLE
Feature Request: logarithmic y axis

### ISSUE THREAD

**Issue by nareddyt** [alexarch21/history-explorer-card#138] opened 2023-02-02 05:24 UTC
Currently the y axis is linear scale. Min and max bounds are configurable.

Can we add an option to change scale to logarithmic function?

I am happy to add in this feature if help is needed, but it will take time to look over the code.

**Comment by alexarch21** [comment] 2023-02-02 12:42
Duplicate of #129

**Closed by alexarch21** 2023-02-02 12:42 UTC
