### ISSUE TITLE
Feature request: Show nearest state on graph hover

### ISSUE THREAD

**Issue by clau-bucur** [alexarch21/history-explorer-card#103] opened 2022-12-09 11:09 UTC
Currently when you hover with the mouse over the graph you see a state only when you're at the exact location (X and Y) of the new state.

Would it be possible to add a way to **always display the nearest state value when hovering**?
Something like Apex charts is doing, or Grafana.
Apex shows the cursor position and marks the state position it with a vertical line so that you know where you are in relation to the displayed state.

I find this a very useful feature for a graph, especially for entities that have rather unfrequent state changes.
It's not so intuitive and easy to find the exact position (on X and Y scale) of the value you want to be displayed.

**Comment by alexarch21** [comment] 2022-12-10 00:20
I agree that this would make sense. I get annoyed myself by this behavior occasionally, especially on mobile. But this needs to be carefully implemented, with the tooltip only appearing when hovering (or tapping) close to the curve. Otherwise it will impede with the swipe / drag scrolling.

**Comment by clau-bucur** [comment] 2022-12-10 11:01
True. You could add another button similar to "Zoom" which would toggle drag scrolling on or off.
Button that can be shown/hidden based on config.

**Comment by alexarch21** [comment] 2022-12-10 12:48
I don't think that adding a new UI element for this would be the right approach. Neither would be a config toggle. This is a feature that would need to work intuitively out of the box.

**Comment by alexarch21** [comment] 2022-12-18 22:42
Tooltip selection was considerably improved in V1.0.41, it should be much easier to find datapoints now. They highlight a lot earlier, the tooltip appears when you hover the highlights. You can also press and hold shift while moving over a graph, this will show all available datapoints on the line.

Feedback welcome.

**Comment by clau-bucur** [comment] 2022-12-21 11:41
Thank you. Indeed it's a big improvement and I like it.

Have not found a way to show all data points on mobile but I guess it's not possible, otherwise mobile experience seems good.

One suggestion: show the tooltip as soon as the nearest data point is selected, not only when you click on the exact location in the graph. 
This will make it even easier to use.

**Comment by alexarch21** [comment] 2022-12-21 14:41
Okay good, I'll close this then.

The delay and behaviour for the tooltip to open is by design, so the tooltip doesn't get too much in the way when you move your mouse around.

**Closed by alexarch21** 2022-12-21 14:41 UTC
Labels: enhancement
