### ISSUE TITLE
*wildcard* user question

### ISSUE THREAD

**Issue by roykrikke** [alexarch21/history-explorer-card#162] opened 2023-03-26 14:41 UTC
I was trying to get the feature below to work. I think I'm doing something wrong, but I don't see the error itself.
_The entity entry field accepts the * wildcard and can automatically add multiple entities that match the provided pattern._

Below is nicely working, my 6 sensors are added.
```
type: custom:history-explorer-card
cardName: historycard-sdm630
defaultTimeRange: 5m
combineSameUnits: true
showUnavailable: true
header: Phase line to neutral volts history
graphs:
  - type: line
    entities:
      - entity: sensor.energy_meters_pv_phase_1_line_to_neutral_volts
      - entity: sensor.energy_meters_pv_phase_2_line_to_neutral_volts
      - entity: sensor.energy_meters_pv_phase_3_line_to_neutral_volts
      - entity: sensor.energy_meters_ev_phase_1_line_to_neutral_volts
      - entity: sensor.energy_meters_ev_phase_2_line_to_neutral_volts
      - entity: sensor.energy_meters_ev_phase_3_line_to_neutral_volts
```

To do this easily and more clearly, I thought I would use the following. This doesn't work and I don't really understand why. Unfortunately I get an **undefined** in the graph.
```
type: custom:history-explorer-card
cardName: historycard-sdm630
defaultTimeRange: 5m
combineSameUnits: true
showUnavailable: true
header: Phase line to neutral volts history
graphs:
  - type: line
    entities:
      - entity: sensor.*line_to_neutral_volts*
```

The one below does work and I expected the same with the item above. 
```
type: custom:history-explorer-card
filterEntities:
  - sensor.*_line_to_neutral_volts*
```

**Can someone help give me advice?** Because I don't see the issue myself.

**Comment by alexarch21** [comment] 2023-03-26 15:13
The entity *entry field* refers to the UI entry field. You can enter wildcards there. It does not refer to the yaml parameters. Wildcards are not (yet) supported on those, mainly because I lack the time to add and test this.

**Comment by roykrikke** [comment] 2023-03-26 15:39
I'm afraid I lack knowledge to fully understand you. Can you explain a bit more about what exactly you mean?

**Comment by alexarch21** [comment] 2023-03-26 20:04
This works:

![image](https://user-images.githubusercontent.com/60828821/227801553-a25fb412-cba2-4ef9-ac68-74a7db95b746.png)

this doesn't:

![image](https://user-images.githubusercontent.com/60828821/227801562-41541fe2-3a29-49fd-ab47-7b64af12601d.png)

I'll see if I can add this for one of the next releases.

**Comment by roykrikke** [comment] 2023-03-26 20:18
Ha now I get it. On top of this:
_filterEntities:
  - sensor.*_line_to_neutral_volts*_

this then for in the yaml file for per-selecting.

It would be great if you could add this feature. Because then history-explorer-card config  is possible.

PS: Shall we turn this issue into a feature request?

**Comment by GrizzlyAK** [comment] 2023-03-26 22:29
+100 on this feature. I think we discussed this before, but can't remember what we ended with, but using the Recorder file information would be handy too if you could read/interpret that. That would reproduce what we previously had with the built-in History, but in a MUCH BETTER format. At least, though, wildcards would be super helpful, even if we need to copy/paste the Recorder file info into the card. Cheers.

**Comment by alexarch21** [comment] 2023-03-26 23:06
Not exactly sure what you mean by recorder file information (no frontend card can read any file on the host system), but if you mean the list of entities that are being actively added to the recorder, then this is available. 

Add this to the config:
```
recordedEntitiesOnly: true
```
If you now type `*` into the entity field and hit the plus button, all entities that are part of the recorder will be added. You can further refine this by adding `filterEntities`. 

If I add a wildcard function to the YAML at some point, then it will behave in exactly the same way. So adding `*` to the entity list while having `recordedEntitiesOnly: true` would add only recorded entities, the same way as it works with the interactive entry field on the UI now. That's what the native history panel did too.

**Comment by GrizzlyAK** [comment] 2023-03-27 00:56
Ah, I remember our previous conversation now about not being able to read the recorder.yaml file, But, if I understand what you say correctly, it seems that HA does provide the Frontend with at least a list of entities that are _defined_ by the Recorder file. If so, then that is just as good. Perhaps in addition to typing * in the entity list with `recordedEntitiesOnly: true`, could there be another flag, like `showAllRecorded: true` that would, in effect, do the same thing as entering a * in the entity list automatically, every time you open it (without having to type that in each time)? That would be persistent?

**Comment by alexarch21** [comment] 2023-03-27 01:24
> it seems that HA does provide the Frontend with at least a list of entities that are defined by the Recorder file. 

Sadly no, it doesn't. I have to cheat a little by issuing a specific call to the database and build the list of recorded entities that way. In practice it's pretty much equivalent with a HA supplied list though.

I'd like to avoid adding settings that will auto populate the list with specific entities. People will end up asking for all kind of unique scenarios and filters for that etc etc. So I'd rather avoid this. Wildcard support is in the code already. So the right way to do this in a clean and logical way is to allow wildcards in YAML entity names. While this sounds easy on a first glance, it can create all kind of weird corner cases, like the entity order on wildcard'ed globs, handling of different graph types within a single wildcard glob, etc. That's why it needs some more time to get this right.

> I just tested this workaround and it seems, for some reason, that the combineSameUnits: true flag isn't being honored when I enter just *, every entity appearing on its own graph, but when I enter something like *temperature* instead, all of them appear on the same graph.

Weird. Did you set `recordedEntitiesOnly` to true ? I suggest you open a separate issue for this. May or may not be a bug.

**Comment by GrizzlyAK** [comment] 2023-03-27 01:36
> While this sounds easy on a first glance,

Actually, I anticipated this would only come with considerably effort, which is why it hasn't been implemented. Lots of ways for this to go sideways. 

>I'd like to avoid adding settings that will auto populate the list with specific entities

I get that. I only suggested it because it is what is most called for by everyone who hates the built-in History in HA since the _improvement_, i.e., to show everything specified in the Recorder file with no further effort. It just seemed like low-hanging fruit since, in my understanding of what you already have working, it would entail an additional flag that effectively populated the entity list with a `*`.

It's just one character, so I can deal!

> Did you set recordedEntitiesOnly to true ?

Yes, and `combineSameUnits: true`. I'll create an issue and post my current code with screenshots. Cheers.

**Comment by sdrapha** [comment] 2023-04-19 22:46
+1 Bump on this feature. I also want wildcard capability on yaml configuration. I tried combining thomas-loven/auto-entities with this card to achieve that goal, BUT, because the `entities:` key on this card is nested inside:
```yaml
graphs: 
  - type: timeline
    entities:
```
it doesn't work, because auto-entities is looking for that key on the root level of the card configuration, not recursive.

As an idea to make this enhancement to this card, instead of creating code from scratch to make use of wildcards. Just changing the way the card configuration keys are structured, so it would be compatible with auto-entities card, which is already tested and true on the wildcard populating job, and very powerfull with many filters.

**Comment by alexarch21** [comment] 2023-04-20 10:12
I have a working prototype with YAMl wildcard support.

Example:
```
graphs:
  - type: line
    entities:
      - entity: sensor.*temperature*
  - type: timeline
    entities:
      - entity: person.*
```
This will add all temperature sensors in a first graph and then all persons in another timeline graph. This syntax gives full control over what goes into what graph and in what order. Entities with types that are incompatible with the their parent type will be skipped. For example, should the `*temperature*` pattern include something that is not a temperature sensor, for example something like `sensor.temperature_control_switch_state`, then it will simply be ignored. It always entity and graph customization in the usual way.

There's another potential way of doing things with an entities key at the root level:
```
entities:
  - entity: sensor.*
  - entity: binary_sensor.*stuff*
```
This syntax comes with problems as it will mix up entities of different (incompatible) types in pretty much random order. For that to work, this syntax would have to mimic the way entities are added dynamically through the UI and would behave in that way too (combineSame Units, customization over `entityOptions` etc). It would allow other custom components like auto-entities to work with this card (although I'm a little surprised that auto-entities doesn't allow the customization of where the entity keys are placed, that would seem like such a basic feature).

To be perfectly honest, I don't really like the second option. It feels like a step backwards and doesn't really fit into the logic of the card (dynamic entities being pretty much added statically). But it would be possible to add if that's the way people want to use this card.

> As an idea to make this enhancement to this card, instead of creating code from scratch to make use of wildcards. Just changing the way the card configuration keys are structured, so it would be compatible with auto-entities card, which is already tested and true on the wildcard populating job, and very powerfull with many filters.

Adding compatibility is one thing (and possible, see above) but I do not want to get into a situation where this card would depend on another custom card/component.

**Comment by sdrapha** [comment] 2023-04-20 15:04
Glad to hear there is a solution in the making, specially one that is self contained which is even better.😀👍

**Comment by roykrikke** [comment] 2023-04-28 16:49
> I have a working prototype with YAMl wildcard support.
> 
> Example:
> 
> ```
> graphs:
>   - type: line
>     entities:
>       - entity: sensor.*temperature*
>   - type: timeline
>     entities:
>       - entity: person.*
> ```
> 
> This will add all temperature sensors in a first graph and then all persons in another timeline graph. This syntax gives full control over what goes into what graph and in what order. Entities with types that are incompatible with the their parent type will be skipped. For example, should the `*temperature*` pattern include something that is not a temperature sensor, for example something like `sensor.temperature_control_switch_state`, then it will simply be ignored. It allows entity and graph customization in the usual way.
> 
> There's another potential way of doing things with an entities key at the root level:
> 
> ```
> entities:
>   - entity: sensor.*
>   - entity: binary_sensor.*stuff*
> ```
> 
> This syntax comes with problems as it will mix up entities of different (incompatible) types in pretty much random order. For that to work, this syntax would have to mimic the way entities are added dynamically through the UI and would behave in that way too (combineSame Units, customization over `entityOptions` etc). It would allow other custom components like auto-entities to work with this card (although I'm a little surprised that auto-entities doesn't allow the customization of where the entity keys are placed, that would seem like such a basic feature).
> 
> To be perfectly honest, I don't really like the second option. It feels like a step backwards and doesn't really fit into the logic of the card (dynamic entities being pretty much added statically). But it would be possible to add if that's the way people want to use this card.
> 
> > As an idea to make this enhancement to this card, instead of creating code from scratch to make use of wildcards. Just changing the way the card configuration keys are structured, so it would be compatible with auto-entities card, which is already tested and true on the wildcard populating job, and very powerfull with many filters.
> 
> Adding compatibility is one thing (and possible, see above) but I do not want to get into a situation where this card would depend on another custom card/component.

How is the development going? Could you use a beta tester? I'm just asking, because I am very curious. :-)

**Comment by alexarch21** [comment] 2023-04-28 22:43
Not much to say, it's working as expected. It's mostly a function of how much of my free time I can put into finalizing this. Right now, preparing my sailboat for the season is getting some priority over this ;) But I guess a release next weekend could be possible.

One thing didn't go as planned: the wildcards will resolve against all entities registered with HA, not only against the ones that are actually in the database. So if you do `sensor.*temperature*` it will add all matching entities, regardless of whether they're in the DB or not (entities that aren't recorded won't appear in the graph, but they will appear as a bubble in the legend). 

Sadly there is no way around that. The HA frontend API does not expose a list of recorded entities. The way I build this list is by directly querying the database, but those results come in with a delay. They're not available at the time the graphs are built. You will have to craft your wildcard strings accordingly, to avoid this.

**Comment by GrizzlyAK** [comment] 2023-04-29 04:40
It's truly sad that this functionality currently exists in the core, but was deemed "undesirable" by one or more people in charge, leaving many to search or develop alternate solutions - where more thought and consideration would have led to an simple OPTION to provide the old, existing functionality along with the new, making the entire user base happy. But it seems those at Nabu Casa have their focus set on making HA the iPhone of home automation where "no instructions needed" and therefore more appealing to the most uninitiated of users who can barely turn on their TV. 

We do very much appreciate your efforts in recreating a functional (and actually USEFUL) history utility in HA to replace what was so carelessly (and crassly) eliminated. Thank you.

**Comment by roykrikke** [comment] 2023-04-29 18:12
> It's truly sad that this functionality currently exists in the core, but was deemed "undesirable" by one or more people in charge, leaving many to search or develop alternate solutions - where more thought and consideration would have led to a simple OPTION to provide the old, existing functionality along with the new, making the entire user base happy. But it seems those at Nabu Casa have their focus set on making HA the iPhone of home automation where "no instructions needed" and therefore more appealing to the most uninitiated of users who can barely turn on their TV.
> 
> We do very much appreciate your efforts in recreating a functional (and actually USEFUL) history utility in HA to replace what was so carelessly (and crassly) eliminated. Thank you.

I couldn't have written this better myself!

**Comment by alexarch21** [comment] 2023-05-05 21:05
Note that bdraco wrote a draft patch to HA 2023.5, linked above, that would solve all the issues discussed here by providing a direct access to the list of recorded entities, without the workaround of a database query.

This patch is work in progress (although it works perfectly on my tests), and there is no guarantee it will be accepted in Core. I hope it will.

**Comment by GrizzlyAK** [comment] 2023-05-05 23:53
That's awesome. I hope Core does accept it, as it would be _really_ disappointing if they didn't. It would be great to have a decent History capability again. Thanks to you both for your work on this.

**Comment by alexarch21** [comment] 2023-05-06 00:45
You can already get the full history capability (and always could), even without the patch, you just have to keep your browser local storage and build your entity list using the UI.

But I know what you mean. It would be a good feature to have in all cases.

**Comment by alexarch21** [comment] 2023-06-23 12:55
Welp, looks like that patch above won't make it into Core. At least there has been pretty much zero traction on this draft. Too bad, it would have been really useful and it works very well.

Anyway, I implemented wildcard support in the card on the upcoming V1.0.47. It comes with a number of limitations though, as discussed above. But things like this are possible:

```
graphs:
  - type: line
    entities:
      - entity: sensor.*temperature*
        fill: rgba(0,0,0,0)
```

![image](https://github.com/alexarch21/history-explorer-card/assets/60828821/7524906d-6a50-4bfb-b66d-dfc84cbeafae)

I'm going to add some more default colors to make it look less like a mess.

**Comment by alexarch21** [comment] 2023-06-24 01:00
I added an optional `exclude` clause to wildcard'ed entities. This will (in part) alleviate the limitations by not having a list of entities actually being recorded by HA:

```
graphs:
  - type: line
    entities:
      - entity: sensor.*temperature*
        exclude:
          - entity: sensor.cpu_temperature
          - entity: '*fridge*'
        fill: rgba(0,0,0,0)
```
This will auto-add all sensors with `temperature` in the name, except for a specific sensor named `sensor.cpu_temperature' and all entities that have 'fridge' in their names.

**Comment by alexarch21** [comment] 2023-06-25 00:40
Wildcard support was added to V1.0.47. See the readme under [YAML configuration for preconfigured graphs](https://github.com/alexarch21/history-explorer-card#yaml-configuration-for-preconfigured-graphs), middle example.

**Comment by alexarch21** [comment] 2023-06-28 09:43
Closing this for now. If problems come up with the new feature, feel free to open a new issue.

**Closed by alexarch21** 2023-06-28 09:43 UTC
Labels: enhancement

**Comment by roykrikke** [comment] 2023-06-29 15:47
Thank you!
