### ISSUE TITLE
Disable line fill by default

### ISSUE THREAD

**Issue by keck9939** [alexarch21/history-explorer-card#53] opened 2022-07-29 21:47 UTC
It would be nice if there was a way to turn off the line fill (shading under graph lines) by default. The fill is annoying on graphs with multiple lines.

**Comment by alexarch21** [comment] 2022-07-29 22:06
You can remove it by something like `fill: 'rgba(0,0,0,0)'`, or any color with a zero alpha value for that matter.

**Comment by keck9939** [comment] 2022-07-29 23:23
I have been able to remove it from individual lines doing that, but it is tedious to go through and set that for each line. What I want is to set things up so that whenever a new dynamic plot is added there is no fill.

**Comment by alexarch21** [comment] 2022-07-30 00:25
Just to clarify this. Are you talking about entities added in the YAML or entities added through the dynamic UI with combine same units set to true ?

**Comment by keck9939** [comment] 2022-07-30 01:40
I'm talking about entities added through the dynamic UI with combine same units set to true.

**Comment by alexarch21** [comment] 2022-07-31 11:18
You can configure the fill color on an entire device classes, as described in the [readme here](https://github.com/alexarch21/history-explorer-card#customizing-dynamically-added-graphs). For example, to remove the fill from all temperature devices (that can auto-combine), you can do this:
```
entityOptions:
  temperature:  # Apply these settings to all temperature sensors 
    fill: rgba(0,0,0,0)
```
You can add other device classes as needed.

**However**, doing this while not supplying a line color in addition to the fill color will result in the lines to turn back to the default gray. This is a bug and will be fixed in the next release.

**Comment by alexarch21** [comment] 2022-08-25 03:01
Fixed in V1.0.24.

**Closed by alexarch21** 2022-08-25 03:01 UTC

**Comment by RogerSelwyn** [comment] 2022-09-15 19:04
I think this change has removed the fill where specified. The code below should have a line with a fill underneath, but it is transparent.

```
  - type: line
    options:
      ymin: 0
    entities:
      - entity: sensor.nest_current_temperature
        lineMode: curves
        name: Current
        color: '#84bb7199'
      - entity: sensor.nest_set_temperature
        lineMode: stepped
        name: Set
        color: '#6592eb'
      - entity: sensor.nest_heating
        lineMode: stepped
        name: Heating
        fill: '#84bb7199
```'

**Comment by alexarch21** [comment] 2022-09-15 23:34
Yes indeed, looks like there was a regression with explicitly defined fill colors. Could you please open a new issue for this?

**Comment by RogerSelwyn** [comment] 2022-09-16 10:22
Created issue #62
