### ISSUE TITLE
only timestamp in export

### ISSUE THREAD

**Issue by robinhoefman** [alexarch21/history-explorer-card#114] opened 2022-12-19 11:40 UTC
Hello,

i would like to export some data to excel with CSV. But i think i am missing something.

i have a device caled P1 meter (home wizard). this consists out of 13 entities.  The most usefull for me ar the following:
- sensor.p1_meter_total_power_import_t1
- sensor.p1_meter_active_power_l1
- sensor.p1_meter_active_power_l2
- sensor.p1_meter_active_power_l3

I can see graph of each for of them in HA via history-explorer-card or just via the history option of HA. 

But during export using the build-in export option in history-eport some doesnt work quit as expected. If i export the first entitie (total_power) it show a CZV-file with date and time stamp and also the data in kWh. Doing the same for the other entities give me only a file with date and time stammp, no other data is include.

somebody a suggestion about what i am missing? Maybe someone is familiar with this issue and know a work around. Thnak in advanced for your support

**Comment by alexarch21** [comment] 2022-12-19 18:42
Can you post the following things:

* The YAML config for the history explorer card
* A screenshot of how the problematic sensors look like as shown by the history explorer card at the time range of interest
* A screenshot of the problematic entities on the HA developer tools -> States.

**Comment by pvoncken** [comment] 2023-01-01 18:39
> I had a similar problem.
I'm using a graph with the calculated value of a PT100 sensor (range 0-25) and the  uncalculated value (range 800-900 = input reading from an arduino board) . 
The the calculated values are perfectly showing inthe CSV but the uncalculated did not.
When i changed the code on my arduino to show the uncalculated value  801 as 80.1 the CSV did show them.
Maybe that can help you.

**Comment by alexarch21** [comment] 2023-01-04 13:55
There's nothing I can do if you do not provide the information asked for above.

**Comment by robinhoefman** [comment] 2023-01-04 14:11
i am on holiday, i will back next week. Sorry!

**Comment by alexarch21** [comment] 2023-01-23 01:27
Closing this due to missing information. Please open a new issue if you have the relevant information to reproduce this.

**Closed by alexarch21** 2023-01-23 01:27 UTC
